package com.turno.crm.model.enums;

public enum NotificationEventType {
    PRICING_APPROVAL_REQUESTED,
    PRICING_DECISION,
    FOLLOW_UP_DUE_TODAY,
    FOLLOW_UP_OVERDUE,
    REGRESSION_REQUESTED,
    REGRESSION_DECISION,
    STALE_DEAL_ALERT,
    NO_NEXT_ACTION_SET,
    DEAL_ARCHIVED,
    DEAL_REACTIVATED,
    DEAL_ASSIGNED_NEW_OWNER,
    DEAL_REASSIGNED_PREVIOUS_OWNER
}
